# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Marketxiv < Formula
  desc "FFXIV Market CLI Tool
"
  homepage "https://github.com/BitsOfAByte/MarketXIV"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/BitsOfAByte/MarketXIV/releases/download/v1.0.0/marketxiv_darwin_amd64.zip"
      sha256 "b0932cabcd1e5cd96a9ccf0c77d6515d681bcdc726c8eca95264ad62402f6bba"

      def install
        bin.install "marketxiv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/BitsOfAByte/MarketXIV/releases/download/v1.0.0/marketxiv_darwin_arm64.zip"
      sha256 "2bd23a84aaf2a4f7dc02c4883607de67e0e8baf0111026a53d34feaa26375f97"

      def install
        bin.install "marketxiv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/BitsOfAByte/MarketXIV/releases/download/v1.0.0/marketxiv_linux_arm.zip"
      sha256 "efc78431d325e993a9e9167b2c6ae33339330138955eee9642772704e3edfef0"

      def install
        bin.install "marketxiv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BitsOfAByte/MarketXIV/releases/download/v1.0.0/marketxiv_linux_arm64.zip"
      sha256 "2eed22f45cb9672eca8d7d6b4fcceb7fcfa3e9cf667822956e8b8fb04f289a9c"

      def install
        bin.install "marketxiv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/BitsOfAByte/MarketXIV/releases/download/v1.0.0/marketxiv_linux_amd64.zip"
      sha256 "fb80a167c5aedab11d38bef01776f52c07a1a2984fed163098c4d93e3fe68f0a"

      def install
        bin.install "marketxiv"
      end
    end
  end
end
