# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Marketxiv < Formula
  desc "FFXIV marketboard for your command line
"
  homepage "https://github.com/BitsOfAByte/MarketXIV"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/BitsOfAByte/MarketXIV/releases/download/v1.0.3/marketxiv_1.0.3_darwin_arm64.zip"
      sha256 "f50829067ff73c471cf7eaa8126fb3aacceb16d426d50614cf40c1cff88c3c1c"

      def install
        bin.install "marketxiv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/BitsOfAByte/MarketXIV/releases/download/v1.0.3/marketxiv_1.0.3_darwin_amd64.zip"
      sha256 "62728591b4e27472ea5aa62de115b1f1489c5f4d672bdff79f6009a8030f73b9"

      def install
        bin.install "marketxiv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BitsOfAByte/MarketXIV/releases/download/v1.0.3/marketxiv_1.0.3_linux_arm64.zip"
      sha256 "b9b30be18ddb38b5dc3e7f45bba12af137b802726a00c289e493c682704f98d7"

      def install
        bin.install "marketxiv"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/BitsOfAByte/MarketXIV/releases/download/v1.0.3/marketxiv_1.0.3_linux_armv6.zip"
      sha256 "70e079d42e8a217b060cef30307cb76f7aec48cb1e2c919341d06df139b6835d"

      def install
        bin.install "marketxiv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/BitsOfAByte/MarketXIV/releases/download/v1.0.3/marketxiv_1.0.3_linux_amd64.zip"
      sha256 "fbf66344cb242ec429d787d18b3fc58acb6578ba3abf52964d1745da6004c438"

      def install
        bin.install "marketxiv"
      end
    end
  end
end
