# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Marketxiv < Formula
  desc ""
  homepage ""
  version "0.8.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/BitsOfAByte/MarketXIV/releases/download/v0.8.1/marketxiv_darwin_amd64.zip"
      sha256 "b1b1c8dfe4dea2d1a75396aa6ac283f4d7aed5423163d9f14eb1c89548c5f336"

      def install
        bin.install "marketxiv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/BitsOfAByte/MarketXIV/releases/download/v0.8.1/marketxiv_darwin_arm64.zip"
      sha256 "a2082533d2d6357745159019e07a82045a82c77048e8468d85e8a1fb4c3818b0"

      def install
        bin.install "marketxiv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BitsOfAByte/MarketXIV/releases/download/v0.8.1/marketxiv_linux_arm64.zip"
      sha256 "2b816f8d772d09069816c813d986a0fe164862f7f17bb3c02faacd67aadf2c16"

      def install
        bin.install "marketxiv"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/BitsOfAByte/MarketXIV/releases/download/v0.8.1/marketxiv_linux_arm.zip"
      sha256 "cc3425a6d02a0ac3b6de4ed4d10c623f1e715f4a20a1c3c5566f6e5284655186"

      def install
        bin.install "marketxiv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/BitsOfAByte/MarketXIV/releases/download/v0.8.1/marketxiv_linux_amd64.zip"
      sha256 "0cf1e87aa82d4f5731c676630f1ea8af2f6c0d17b6916995bb459f44422f8a55"

      def install
        bin.install "marketxiv"
      end
    end
  end
end
